# ==============================================================================
# Hyprdark - Modular Hyprland Master Configuration
# Clean, modular, engineering-grade setup tailored for cybersecurity workflows.
# ==============================================================================

# Default Application Shortcuts
$terminal    = kitty
$fileManager = thunar
$menu        = rofi -show drun -theme ~/.config/rofi/theme.rasi
$browser     = brave
$editor      = subl

# Sourced Sub-configurations
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/look_and_feel.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
